-- DROP TRIGGER trg_kierunki;
-- DROP TRIGGER trg_stopnie;
-- DROP TRIGGER trg_nazwy_kier;
-- DROP TRIGGER trg_podgrupy;
-- DROP TRIGGER trg_grupy;

DROP TABLE statystyki CASCADE CONSTRAINTS;

DROP TABLE kierunek CASCADE CONSTRAINTS;
DROP TABLE stopien CASCADE CONSTRAINTS;
DROP TABLE nazwa_kierunkow CASCADE CONSTRAINTS;
DROP TABLE podgrupa CASCADE CONSTRAINTS;
DROP TABLE grupa CASCADE CONSTRAINTS;

DROP SEQUENCE kierunki_seq;
DROP SEQUENCE stopnie_seq;
DROP SEQUENCE nazwy_kier_seq;
DROP SEQUENCE podgrupy_seq;
DROP SEQUENCE grupy_seq;

DROP TABLE uczelnia CASCADE CONSTRAINTS;
DROP TABLE miasto CASCADE CONSTRAINTS;
DROP TABLE wojewodztwo CASCADE CONSTRAINTS;

DROP TABLE absolwenci CASCADE CONSTRAINTS;
DROP TABLE studenci CASCADE CONSTRAINTS;


