postgres:
  host: localhost
  port: 5432
  dbname: postgres
  user: postgres
  password: postgres
uni_dataset:
  path: data/raw/uczelnie_data_set.xlsx
oracle:
  host: localhost
  port: 1521
  service_name: xe
  user: hurtownia
  password: hurtownia
instant_client:
  path: C:\oraclexe\instantclient_23_7
json:
  path: "data/raw/json/fields_of_study_data.json"